### ISSUE TITLE
stub out instructor materials section

### ISSUE THREAD

**Issue by nicholasjhorton** [mdsr-book/mdsr-book.github.io#12]
Might you be willing to stub out a draft of how the instructor materials can be put onto the website (using the "text as data" chapter materials as an example)?  I've included the URL for the video: https://youtu.be/sp25j9WaqwA and have added the files into a new folder here called "instructor".

**Comment by beanumber** [comment]
Sure, but I'm not sure what you're asking. 

The pages you added are live now:

http://mdsr-book.github.io/instructor/text.html

However, they won't be compiled by `make`, since they are in a subdirectory. If you want them to have the same look-and-feel as the rest of the website, it might be better to put them back in the root directory. If you don't care about that, you can leave them where they are, but you'll have to compile each one manually. 

To add a link to these in the header, look at `_site.yml`. You'll see what to do.

**Comment by beanumber** [comment]
Is this what you had in mind? (http://mdsr-book.github.io/instructor.html)

**Comment by nicholasjhorton** [comment]
Close (and very helpful: thanks for putting this together).  

Check out my revisions (which are now pushed).  Note that the Rmd files need to be processed through rawgit to avoid mangled YAML headers!

> On Jul 19, 2017, at 10:30 AM, Ben Baumer <notifications@github.com> wrote:
> 
> Is this what you had in mind? (http://mdsr-book.github.io/instructor.html)
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

Nicholas Horton 
Professor of Statistics
Department of Mathematics and Statistics, Amherst College
PO Box 5000, AC #2239
Amherst, MA 01002-5000
